
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./writable:/var/www/html/writable
    environment:
      - CI_ENVIRONMENT=development
      - APP_BASE_URL=http://localhost:8000
      - database.default.hostname=mysql
      - database.default.database=contact_management
      - database.default.username=root
      - database.default.password=
      - database.default.DBDriver=MySQLi
    depends_on:
      - mysql
    networks:
      - ci4-network

  mysql:
    image: mysql:8.0
    container_name: ci4_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: contact_management
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ci4-network

volumes:
  mysql-data:
    driver: local

networks:
  ci4-network:
    driver: bridge